// Golden-parity harness for the hue game math (dev-plan-2026-07-21 P0-0).
// Compiles the SAME ColorConvert.swift the app ships, then asserts against
// values generated by the web implementation (src/lib/screen-test.ts vitest
// expectations). Run:
//   swiftc ios/ColorArchive/Utils/ColorConvert.swift ios/scripts/hue-parity-main.swift -o /tmp/hue-parity && /tmp/hue-parity
// Exits non-zero on any mismatch.

import Foundation

// Web goldens, generated 2026-07-21 via:
//   npx tsx -e "import{generateHueChips}from'./src/lib/screen-test';console.log(generateHueChips().map(c=>c.hex))"
let webChipHexes = [
    "#73a9e1", "#7da6e3", "#88a3e4", "#92a0e3", "#9b9de2", "#a49adf",
    "#ad97db", "#b594d6", "#bd91cf", "#c48fc8", "#ca8dc1", "#cf8cb8",
]
// Full-12 scramble order and its score, per web scrambleChips/hueArrangementScore.
let webScramble12 = [7, 2, 9, 4, 0, 11, 5, 1, 8, 3, 10, 6]
let webScore12 = 54

@main
struct HueParity {
    static var failures = 0

    static func check(_ name: String, _ ok: Bool) {
        if ok {
            print("ok  \(name)")
        } else {
            print("FAIL \(name)")
            failures += 1
        }
    }

    static func main() {
        let chips = HueGameMath.generateChips()
        check("chip count == 12", chips.count == 12)
        for (i, chip) in chips.enumerated() {
            check("chip \(i) hex \(chip.hexValue) == web \(webChipHexes[i])", chip.hexValue == webChipHexes[i])
        }

        // Score parity: full-12 scramble (web golden) + perfect + reversed-perfect.
        let scrambled12 = webScramble12.map { chips[$0] }
        check("score(scramble12) == \(webScore12)", HueGameMath.score(scrambled12) == webScore12)
        check("score(perfect) == 0", HueGameMath.score(chips) == 0)
        check("score(reversed) == 0", HueGameMath.score(chips.reversed()) == 0)

        // Middle-only scramble: anchors preserved, middle is a permutation of 1…10.
        let game = [chips[0]] + HueGameMath.scrambleMiddle(chips) + [chips[11]]
        check("game count == 12", game.count == 12)
        check("anchor start == 0", game.first?.trueIndex == 0)
        check("anchor end == 11", game.last?.trueIndex == 11)
        check("middle is perm of 1…10", Set(game.dropFirst().dropLast().map(\.trueIndex)) == Set(1...10))
        check("middle scramble is not already solved", game.map(\.trueIndex) != Array(0...11))

        if failures > 0 {
            print("\n\(failures) parity failure(s)")
            exit(1)
        }
        print("\nAll hue-game parity checks passed.")
    }
}
