import type { Metadata } from "next";
import { SiteHeader } from "@/src/components/site-header";
import { StructuredDataScript } from "@/src/components/structured-data-script";
import { MoodPalettePage } from "@/src/components/mood-palette-page";

export const metadata: Metadata = {
  title: { absolute: "AI Mood Palette Generator | ColorArchive" },
  description:
    "Describe a mood, scene, or emotion and get a beautiful 5-color palette generated by AI. Try 'dark academia', 'arctic morning', or anything you imagine.",
  alternates: { canonical: "/mood-palette/" },
  openGraph: {
    title: "AI Mood Palette Generator | ColorArchive",
    description: "Turn any mood or scene into a beautiful color palette. Powered by AI.",
    images: ["https://colorarchive.me/og-image-v1.png"],
  },
};

const structuredData = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "AI Mood Palette Generator",
  applicationCategory: "DesignApplication",
  operatingSystem: "Any",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
  url: "https://colorarchive.me/mood-palette/",
  description:
    "Describe a mood, scene, or emotion and get a beautiful 5-color palette generated by AI. Try 'dark academia', 'arctic morning', or anything you imagine.",
};

const breadcrumbData = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "ColorArchive", item: "https://colorarchive.me/" },
    { "@type": "ListItem", position: 2, name: "Mood Palette", item: "https://colorarchive.me/mood-palette/" },
  ],
};

export default function MoodPaletteRoute() {
  return (
    <>
      <SiteHeader currentPath="/mood-palette" />
      <StructuredDataScript data={[structuredData, breadcrumbData]} />
      <MoodPalettePage />
    </>
  );
}
