import type { Metadata } from "next";
import { SiteHeader } from "@/src/components/site-header";
import { MoodPalettePage } from "@/src/components/mood-palette-page";

export const metadata: Metadata = {
  title: { absolute: "AI Mood Palette Generator | ColorArchive" },
  description:
    "Describe a mood, scene, or emotion and get a beautiful 5-color palette generated by AI. Try 'dark academia', 'arctic morning', or anything you imagine.",
  alternates: { canonical: "/mood-palette/" },
  openGraph: {
    title: "AI Mood Palette Generator | ColorArchive",
    description: "Turn any mood or scene into a beautiful color palette. Powered by AI.",
    images: ["https://colorarchive.me/og-image-v1.png"],
  },
};

export default function MoodPaletteRoute() {
  return (
    <>
      <SiteHeader currentPath="/mood-palette" />
      <MoodPalettePage />
    </>
  );
}
