import { describe, expect, it } from "vitest";
import { generateColorFromWord } from "@/src/lib/word-color";
import seedSnapshot from "./fixtures/word-color-seeds.json";

const HEX_PATTERN = /^#[0-9A-Fa-f]{6}$/;

describe("generateColorFromWord", () => {
  describe("determinism", () => {
    it("returns the same result for identical input across calls", () => {
      const a = generateColorFromWord("ocean");
      const b = generateColorFromWord("ocean");
      expect(a).toEqual(b);
    });

    it("is case-insensitive", () => {
      const lower = generateColorFromWord("sunset");
      const upper = generateColorFromWord("SUNSET");
      const mixed = generateColorFromWord("SuNsEt");
      expect(lower).toEqual(upper);
      expect(lower).toEqual(mixed);
    });

    it("trims whitespace", () => {
      const clean = generateColorFromWord("forest");
      const padded = generateColorFromWord("  forest  ");
      expect(clean).toEqual(padded);
    });
  });

  describe("collision resistance", () => {
    const words = [
      "red", "blue", "green", "yellow", "purple",
      "ocean", "forest", "sunset", "midnight", "coral",
      "cat", "dog", "bird", "fish", "tree",
    ];

    it("produces distinct hex values for common words", () => {
      const hexes = words.map((w) => generateColorFromWord(w)!.hex);
      const unique = new Set(hexes);
      expect(unique.size).toBe(words.length);
    });
  });

  describe("output format", () => {
    it("returns valid hex for the main color", () => {
      const result = generateColorFromWord("hello")!;
      expect(result.hex).toMatch(HEX_PATTERN);
    });

    it("returns exactly 5 variants", () => {
      const result = generateColorFromWord("world")!;
      expect(result.variants).toHaveLength(5);
    });

    it("returns valid hex for every variant", () => {
      const result = generateColorFromWord("spectrum")!;
      for (const variant of result.variants) {
        expect(variant.hex).toMatch(HEX_PATTERN);
      }
    });

    it("includes expected variant labels", () => {
      const result = generateColorFromWord("palette")!;
      const labels = result.variants.map((v) => v.label);
      expect(labels).toEqual(["Mist", "Glow", "Base", "Deep", "Accent"]);
    });

    it("normalizes the token in the output", () => {
      const result = generateColorFromWord("  Hello  ")!;
      expect(result.token).toBe("hello");
    });
  });

  describe("edge cases", () => {
    it("returns null for empty string", () => {
      expect(generateColorFromWord("")).toBeNull();
    });

    it("returns null for whitespace-only string", () => {
      expect(generateColorFromWord("   ")).toBeNull();
    });

    it("handles single character input", () => {
      const result = generateColorFromWord("a")!;
      expect(result.hex).toMatch(HEX_PATTERN);
      expect(result.variants).toHaveLength(5);
    });

    it("handles long input", () => {
      const result = generateColorFromWord("a".repeat(1000))!;
      expect(result.hex).toMatch(HEX_PATTERN);
      expect(result.variants).toHaveLength(5);
    });
  });
});

describe("short-input hash repair", () => {
  /**
   * `hash * 31 + char` leaves the high bits empty for very short inputs, and the
   * saturation/lightness channels are sliced off those bits. Every single ASCII
   * character therefore came out with lightness pinned to exactly 32 and a hue
   * equal to its raw char code — "a" through "z" were all the same dark green,
   * "0" through "9" all the same olive. An avalanche step now runs for hashes
   * below 256.
   */
  it("single letters no longer collapse to one lightness", () => {
    const letters = "abcdefghijklmnopqrstuvwxyz".split("");
    const lightnesses = new Set(letters.map((l) => generateColorFromWord(l)!.lightness));
    // Was exactly 1. Anything in double digits means the channel is live again.
    expect(lightnesses.size).toBeGreaterThan(10);
  });

  it("digits spread across the wheel instead of one 9-degree wedge", () => {
    const hues = "0123456789".split("").map((d) => generateColorFromWord(d)!.hue);
    const spread = Math.max(...hues) - Math.min(...hues);
    expect(spread).toBeGreaterThan(180);
  });

  /**
   * EVERY PUBLISHED WORD, NOT SIX HAND-PICKED ONES.
   *
   * The first attempt at the short-input repair used a 4096 threshold, reasoning
   * from the a-z bounds that nothing real lived below it. The seed list contains
   * the 2-character word "ai" (hash 3112), so that threshold silently recoloured
   * a live page — title, h1, meta description, JSON-LD and OG card — and the
   * pinned-value test of the day contained no 2-character word, so it passed.
   *
   * The fixture is the colour every one of these words returned BEFORE any hash
   * change, generated by replaying the original implementation. Any future edit
   * to hashString now has to face all 474 published pages at once, which is the
   * only check that actually matches the promise the pages themselves make.
   */
  it("every published seed word keeps the colour its page was built with", () => {
    const changed: string[] = [];
    for (const [word, hex] of Object.entries(seedSnapshot)) {
      const actual = generateColorFromWord(word)?.hex;
      if (actual !== hex) changed.push(`${word}: ${hex} -> ${actual}`);
    }
    expect(changed, `published word pages recoloured:\n${changed.join("\n")}`).toEqual([]);
  });

  /**
   * A single Han character is a real word and was never degenerate — U+4E00 is
   * 19968, far above the 256 cutoff — so it must be untouched. An early attempt
   * used a 65536 threshold and recoloured every one of them.
   */
  it.each([
    ["cat", "#932A49"],
    ["爱", "#B3C379"],
    ["受", "#87A4ED"],
  ])("%s keeps the colour it has always returned", (word, hex) => {
    expect(generateColorFromWord(word)!.hex).toBe(hex);
  });
});
